### ISSUE TITLE
Issue with currencies.json and localeFormats.json

### ISSUE THREAD

**Issue by domoconnell** [smirzaei/currency-formatter#35]
I've been using this in a small application for a few months, on a new deployment I found it doesn't work anymore. 
I'm getting issues with currencies.json and localeFormats.json

ERROR in ./~/currency-formatter/currencies.json
Module parse failed: /node_modules/currency-formatter/currencies.json Unexpected token (2:6)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (2:6)

ERROR in ./~/currency-formatter/localeFormats.json
Module parse failed: /node_modules/currency-formatter/localeFormats.json Unexpected token (2:8)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (2:8)

The issues seem to have come about since a few pull requests were merged at the start of Feb.

Any ideas?

**Comment by smirzaei** [comment]
Could you tell us a bit about your environment?
For now I'd suggest using `1.0.8` version.

cc @edorivai

**Comment by edorivai** [comment]
Is that a webpack error? If so did you try adding a json loader? I'm on a phone now, can take a proper look tomorrow.

**Comment by edorivai** [comment]
So I think I've verified this is a webpack error. It occurs because, by default, webpack 1 doesn't handle JSON files. If you want to use the latest version of this library, there are two ways of fixing this within your webpack environment:

1. Use the webpack [JSON loader](https://github.com/webpack-contrib/json-loader)
2. Migrate to [webpack 2](https://webpack.js.org/guides/migrating/), which handles JSON by default

@smirzaei, do you consider this as a breaking change?

**Comment by domoconnell** [comment]
@edorivai Thanks very much. It was indeed a web pack loader issue. I've just added the json loader which works great. I wouldn't have thought it was a breaking change, I was just being stupid ;-) Up to you though.

**Comment by smirzaei** [comment]
@edorivai I don't think we should consider this as a breaking change, since it's happening only in webpack1. Also thank you very much for helping out.

@domoconnell Glad to hear that this issue is fixed, sorry for the inconvenience!

I guess there is no point in keeping this open then.
